### ISSUE TITLE
port plugin to Buble?

### ISSUE THREAD

**Issue by leeoniya** [rpetrich/babel-plugin-transform-async-to-promises#16]
hi @rpetrich,

do you have any time or interest in porting this plugin to Buble?

see https://github.com/Rich-Harris/buble/pull/125

**Comment by rpetrich** [comment]
I'm not as familiar with Buble's model as I am with Babel's, but as I understand it the AST is only used for traversal and any transformations that a plugin performs has to be applied as text edits over the source. As implemented, this plugin relies on many of Babel's features to make complex transformations to the AST and to rebuild as text edits would be a pretty substantial rewrite that I'm not interested in taking on.

**Comment by leeoniya** [comment]
ok, thanks!
