### ISSUE TITLE
Any plan to support top level await ?

### ISSUE THREAD

**Issue by dmail** [rpetrich/babel-plugin-transform-async-to-promises#26]
For instance, given

```js
const a = await 10
console.log(a)
```

We would get something like

```js
Promise.resolve(10).then((value) => {
  console.log(value)
})
```

**Comment by rpetrich** [comment]
This is something I'd like to support, but it will require integration with loaders/bundlers and is thus quite a ways off.

**Comment by dmail** [comment]
Cool will come back at you with some systemjs integration examples.

**Comment by rpetrich** [comment]
Note to self: the associated babel issue is babel/babel#9426

**Comment by dmail** [comment]
At least for esmodules, there is no need to integrate with loaders/bundlers because 

```js
<script type="module">
  const value = await Promise.resolve(42)
  console.log(value)
</script>
```

Could become 

```js
<script type="module">
  Promise.resolve(42).then((value) => {
    console.log(value)
  })
</script>
```

Right?

**Comment by rpetrich** [comment]
I think the simple case where a module doesn't export anything could be converted as you suggest, if module load order and failure is deemed unimportant. For proper support modules need a way to "return" a promise so that top level await can hold up the load of the module until all top level awaits either resolve or reject. An example of the loader order is as follows:

If module A does the following:
```javascript
await fetch("https://example.com");
console.log("module A");
```
And module B does the following:
```javascript
await import("module-a.mjs");
console.log("module B");
```
The "module A" message should be logged before "module B" and if the fetch fails, no messages should be logged.

This becomes more important where module A has exports that reference an awaited value like such:
```javascript
export const data = await (await fetch("https://somedataset.com/")).json();
```
And module B uses those exports:
```javascript
import data from "module-a.mjs";
console.log(data);
```

It might be that I've made a more strict interpretation of module loading than the spec requires, and I'm not sure how circular imports are supposed to work top level await. @dmail did I get this right?

**Comment by dmail** [comment]
You are right.

When I opened this issue my problem was the following: 

I want to convert a file using async/await to something odl browsers can execute using babel.

```js
async function doStuff() {
  return await Promise.resolve(42)
}

await doStuff()
```

When using babel with  transform-async-to-promises + systemjs plugins I get the following code:

```js
System.register([], function (_export, _context) {
  var doStuff
  function _await(value, then, direct) {
    if (direct) {
      return then ? then(value) : value
    }

    if (!value || !value.then) {
      value = Promise.resolve(value)
    }

    return then ? value.then(then) : value
  }
  function _async(f) {
    return function () {
      for (var args = [], i = 0; i < arguments.length; i++) {
        args[i] = arguments[i]
      }

      try {
        return Promise.resolve(f.apply(this, args))
      } catch (e) {
        return Promise.reject(e)
      }
    }
  }
  return {
    execute: async function () {
      doStuff = _async(function () {
        return Promise.resolve(42)
      })
      await doStuff()
    },
  }
})
```

The issue being that **there is still some async/await in the code generated**. That's because top level await is kept untouched and systemjs plugin uses the async keyword.

The solution I found was to **re-run babel a second time with transform-async-to-promises** to get code without async/await.

**Comment by rpetrich** [comment]
@dmail that code snippet helped a lot and uncovered to me that SystemJS will wait for promises returned by modules' execute functions. I've added experimental support for top level await with SystemJS in 0.8.17 when the `topLevelAwait` option is set to `"return"`. Could you experiment with this new option and let me know how well it works in some of your examples?

**Comment by dmail** [comment]
I will try that soon and let you know, thank you

**Comment by dmail** [comment]
I have tried and got 2 errors: one with rollup the other with transform-react-jsx.

For the first error I would like to be able to get the behaviour of 0.8.16 into 0.8.17 (ignoring top level await). Maybe something like topLevelAwait: 'ignore' to allow top level await but keep it untouched.

For the second I need to prepare file with steps to reproduce to help us understand what is going on

**Comment by rpetrich** [comment]
@dmail `topLevelAwait: 'ignore'` exists and does what you've described, though I haven't documented it yet: https://github.com/rpetrich/babel-plugin-transform-async-to-promises/blob/v0.8.17/async-to-promises.ts#L55

I examined some of your tests and am not sure what to do about test/workers/main.html. It's not possible to support exporting from the tail of an await expression without being able to "hold" the completion of the module until some promise or chain of promises resolve. For systemjs this works by returning a promise at the top level, but for bare ES6 modules without some sort of import/export rewrite this is not possible. I've added some code to report an error whe `export` is used in a module's top level continuation when the `topLevelAwait` mode is `simple` (see 16428cb3e4a791bad9b8718665dd02fac3077b78)

**Comment by dmail** [comment]
> for bare ES6 modules without some sort of import/export rewrite this is not possible

Except for tests, I have not yet faced a case where I need top level await + export in the same file. But for these files, I rely on SystemJS + async-to-promises to make code compatible with runtimes without top level await. I am not expecting async-to-promises to handle this alone.

I have made some changes in my PR upgrading async-to-promises to 0.8.17, I should be able to merge it soon thanks to your help.

**Comment by rpetrich** [comment]
Looks like you figured out the remaining issues and got it merged 🎉 

Thanks for pushing for top-level await and providing details on SystemJS
