### ISSUE TITLE
Issue with referencing `this` in async method default arguments

### ISSUE THREAD

**Issue by jimmydief** [rpetrich/babel-plugin-transform-async-to-promises#28]
Thanks for all of the work on this awesome plugin! I came across an instance where the plugin, when combined with `@babel/preset-env`, generates some invalid code.

Original code:
```js
class A {
	async a(x = this.x())  {}
}
```

The issue is that the line that applies the default arg references `_this` but appears outside of the scope where `_this` is defined.

Generated code:
```js
"use strict";

function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return right[Symbol.hasInstance](left); } else { return left instanceof right; } }

function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

var A =
/*#__PURE__*/
function () {
  function A() {
    _classCallCheck(this, A);
  }

  _createClass(A, [{
    key: "a",
    value: function () {
      var x = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : _this.x();
      return function () {
        var _this = this;
      }.apply(this);
    }
  }]);

  return A;
}();
```

Heres' my Babel config:
```js
{
	presets: ['env'],
	plugins: ['transform-async-to-promises']
}
```

[Here it is on the Babel REPL.](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAECC0G8BQBISBPAdsaYAUAHtALzQAuAFgJYQB0BeAlI9Ikq6-xwL5LdA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.4.3&externalPlugins=babel-plugin-transform-async-to-promises%400.8.9)

And some version info:
`node`: 8.11.1
`@babel/core`: 7.3.3
`@babel/preset-env`: 7.3.1
`babel-plugin-transform-async-to-promises`: 0.8.5

**Comment by rpetrich** [comment]
@jimmydief Thanks for sending this test case. It exposed the lack of proper support for default arguments. This should be remedied in 0.8.10

**Comment by jimmydief** [comment]
Thanks again for the quick fix!
