### ISSUE TITLE
Reliance on Symbol

### ISSUE THREAD

**Issue by developit** [rpetrich/babel-plugin-transform-async-to-promises#30]
Generator support relies on `Symbol` without the detection used for the other two usages:

https://github.com/rpetrich/babel-plugin-transform-async-to-promises/blob/2088950784580000afa20b9db7e72123103bd875/helpers.js#L635

**Comment by rpetrich** [comment]
Including a full polyfill for `Symbol` would add a lot of bulk. The workaround I came up with was to downgrade to using a string key instead when `Symbol` is unavailable. To be compatible with regenerator, `"@@iterator"` and `"@@asyncIterator"` will be used in 0.8.11 if `Symbol` is unavailable.
