### ISSUE TITLE
Extra non-returned Promise.resolve() in try/catch (dead code)

### ISSUE THREAD

**Issue by developit** [rpetrich/babel-plugin-transform-async-to-promises#31]
Within a try/catch block, there's a Promise.resolve() that is always dead code. Seems like it needs to be returned.

**0.8.10:**

```js
function(n) {
    "function" == typeof define && define.amd ? define(n) : n()
}(function() {
    ! function() {
        try {
            console.log("foo")
        } catch (n) {
            return Promise.reject(n)
        }
    }()
});
```

**0.8.11:**

```js
! function(e) {
    "function" == typeof define && define.amd ? define(e) : e()
}(function() {
    ! function() {
        try {
            console.log("foo"), Promise.resolve()
        } catch (e) {
            return Promise.reject(e)
        }
    }()
});
```

**Comment by rpetrich** [comment]
eca3a5919354091b8f9eb24c82e215c033b5d0e3 fixed a few cases where non-promises could be returned when `inlineHelpers` was enabled, but this lead to longer code with IIFEs. I've done a bunch of work in 0.8.12 to optimize IIFEs specifically.

**Comment by ForsakenHarmony** [comment]
`try{console.log(\\"foo\\")}catch(o){Promise.reject(o)}`

there seems to be an orphaned `Promise.reject` now

**Comment by ForsakenHarmony** [comment]
Wait I'm not sure if that's orphaned given that it's an inlined iife 🤔, but still kinda confusing

**Comment by rpetrich** [comment]
@ForsakenHarmony Promise rejection has side effects in some environments, so it can’t be safely optimized away.

**Comment by developit** [comment]
Awesome, and good catch about the reject() being side-effecting. The original fix I'd thought of for microbundle was just going to be to mark Promise.resolve() as "pure" so Terser would strip it, so this saves us having to do that!
