### ISSUE TITLE
Crashes when using include, exclude or other glob pattern options in babel configuration

### ISSUE THREAD

**Issue by rjgotten** [rpetrich/babel-plugin-transform-async-to-promises#35]
When using `include`, `exclude` or other Babel configuration options that use glob file matching, this plugin causes Babel to throw the error:
```
Configuration contains string/RegExp pattern, but no filename was passed to Babel
```

Root cause of the problem lies here:

https://github.com/rpetrich/babel-plugin-transform-async-to-promises/blob/a1a6dbeccd8d7ba7e42c062071ecbb4cf5cb9782/async-to-promises.ts#L2892-L2899

The `parse` call internally loads and uses the available Babel configuration, but does not pass the `filename` option. You **must** pass a dummy non-null; non-whitespace filename to avoid problems here with Babel configurations that use `include`, `exclude` or similar glob options.

After fixing this problem, the _same_ problem is triggered a 2nd time, by the `transformFromAst` call.  While it specifies `babelrc:false` to block external configuration from being used, it forgets to set `configFile:false` as well. The first only stops `.babelrc` files from being processed, the second is needed to stop `babel.config.js` files from being processed.

**Comment by rpetrich** [comment]
Thanks for the _very_ complete bug report. This should be resolved in 0.8.13
