### ISSUE TITLE
Empty async functions do not return a Promise with inlineHelpers: false

### ISSUE THREAD

**Issue by scq** [rpetrich/babel-plugin-transform-async-to-promises#36]
If you write an empty async function it gets compiled to code that does not return a promise:

```const f = async () => {};``` is compiled to ```const f = function () {}```.

The same thing happens with, say `async () => { const x = 1; }`, but not with `async () => { foo(); }`. Enabling inlineHelpers seems to fix it.

**Comment by rpetrich** [comment]
Good catch. This has been added to the test suite and resolved in 0.8.13
