### ISSUE TITLE
"XXX" is not declared in Babel's scope tracker

### ISSUE THREAD

**Issue by Darmody** [rpetrich/babel-plugin-transform-async-to-promises#38]
![屏幕快照 2019-08-15 14 33 14](https://user-images.githubusercontent.com/6788752/63077540-3601bc00-bf6b-11e9-8e28-d20daedf7f30.png)

export async function in ts get this warning.

**Comment by rpetrich** [comment]
Can you attach a test case? On the surface this issue doesn’t seem like a problem with async-to-promises

**Comment by Darmody** [comment]
Because My repo is private, I can't upload it. And I can't reproduce it when setup a demo...
But warning disappear when I remove the plugin.

https://github.com/babel/babel/issues/10264 does this helpful?

**Comment by rpetrich** [comment]
I'll review the source to make sure all declarations are being registers, but I think they already should be. If you could get a repro case together that would make it much easier to resolve.

**Comment by Darmody** [comment]
> I'll review the source to make sure all declarations are being registers, but I think they already should be. If you could get a repro case together that would make it much easier to resolve.

Thanks a lot! I keep trying too.

**Comment by Darmody** [comment]
![屏幕快照 2019-08-16 19 12 22](https://user-images.githubusercontent.com/6788752/63164098-ebab3880-c059-11e9-82bd-ef277ce63018.png)

Hi, @rpetrich  I figure out warning disappear when I remove all variable definition before the async function.

Once I add variable definition before, warning show up.

Hope this is helpful

**Comment by Darmody** [comment]
![屏幕快照 2019-08-16 19 15 51](https://user-images.githubusercontent.com/6788752/63164201-48a6ee80-c05a-11e9-9825-f23a38326b47.png)

This is my babel config

**Comment by Darmody** [comment]
https://github.com/Darmody/async-to-promise-demo

@rpetrich Here is a simple reproduce demo

**Comment by rpetrich** [comment]
Thanks for providing a repro. This has now been fixed in master.
