### ISSUE TITLE
Undeclared variables being assigned when used with preset env targeting ES5

### ISSUE THREAD

**Issue by i-like-robots** [rpetrich/babel-plugin-transform-async-to-promises#45]
When using the `babel-plugin-transform-async-to-promises` along with `@babel/preset-env` targeting an ES5 environment (such as IE 11) variables can be assigned without first being declared which causes the following error/s:

```
ReferenceError: assignment to undeclared variable varname
```

I have created a minimum test case demonstrating this issue here: https://github.com/i-like-robots/broken-babel-async-await-transform-test-case

There appears to be several ways to mitigate the issue as manifested in the example above:

- Change the target to an ES6 compatible environment so that the variable declarations to not need transforming to use `var` syntax (not an option for us)
- Move the `export default` statement to another line (most practical but in our case would require changes to number of code bases across our projects)
- Avoid using certain variables within the scope of a function generated by this plugin (probably not possible)

This may be a duplicate of #38

**Comment by rpetrich** [comment]
Babel's scope tracking got more strict in babel 7.6; this is now remedied in master and will be in the next release.

**Comment by i-like-robots** [comment]
Thank you @rpetrich 👍
