### ISSUE TITLE
break inside a try block does not work correctly

### ISSUE THREAD

**Issue by redneb** [rpetrich/babel-plugin-transform-async-to-promises#46]
Consider the following snippet where we are breaking out of loop from inside a `try` block:

	async function foo() {
		while (true) {
			try {
				await null; // important
				console.log(1);
				break;
			}
			catch {}
			console.log(2);
		}
	}
	
	foo();

The second `console.log` should never run because we exit the `while` loop prior to that. But using `babel-plugin-transform-async-to-promises` and running the output of babel, it executes both `console.log` statements and then exits the loop:

    $ ./node_modules/.bin/babel test.js | node
    1
    2

Contrast that to:

    $ node test.js 
    1

**Comment by rpetrich** [comment]
Thanks for the test case. This is now in resolved in 0.8.15
