### ISSUE TITLE
break does not work?

### ISSUE THREAD

**Issue by redneb** [rpetrich/babel-plugin-transform-async-to-promises#47]
Consider the following snippet:

    (async () => {
    	while (true) {
    		console.log("loop");
    		await null; // important
    		break;
    	}
    })();

If I run this with node it only prints the string once:

    $ node test.js 
    loop

but if I run it via `transform-async-to-promises` I get an infinite loop:

    $ ./node_modules/.bin/babel test.js | node
    loop
    loop
    loop
    loop
    loop
    ... (keeps going indefinetly)

**Comment by imkost** [comment]
I encounter the same problem. Hope it will be fixed. For now I use `for (;;)` instead of `while (true)`, works as expected
