### ISSUE TITLE
Named async function expression returning a variable value does not return a promise

### ISSUE THREAD

**Issue by scq** [rpetrich/babel-plugin-transform-async-to-promises#50]
Minimal repro case:

```
const foo = async function _foo() {
  return bar;
};
```

Output:
```
const foo = function _foo() {
  try {
    return bar;
  } catch (e) {
    return Promise.reject(e);
  }
};
```

`return bar()` will also reproduce it.

Deleting `const foo = ` (changing from a function expression to a function declaration), removing the name of the function, or returning a constant value (e.g. `3`) will cause it to behave correctly.

**Comment by scq** [comment]
Turning on `inlineHelpers` also seems to resolve it.

**Comment by scq** [comment]
Similar issue here:

```js
const foo = async function _foo(arg) {
  if (arg.length === 0) {
    return;
  }
};
```
Becomes:
```js
const foo = function _foo(arg) {
  try {
    if (arg.length === 0) {
      return;
    }

    return (0, _helpers._await)();
  } catch (e) {
    return Promise.reject(e);
  }
};
```
Like before, `inlineHelpers` resolves it.

**Comment by niksy** [comment]
I can confirm the bug, last version without the bug is `0.8.13`.
