### ISSUE TITLE
externalHelpers undocumented?

### ISSUE THREAD

**Issue by shirotech** [rpetrich/babel-plugin-transform-async-to-promises#52]
Was wondering what does it actually do? Seems to optimise the helpers so it doesn't duplicate?
Is it safe to turn on? Thanks!

**Comment by kentcdodds** [comment]
Thanks for mentioning the option! I was going to ask for this feature.

I'll make a pull request to add it to the docs and we'll see what @rpetrich does with it :)

**Comment by shirotech** [comment]
Thanks @kentcdodds guess I’ll close this.
