### ISSUE TITLE
helpers.js is not ES5 compatible

### ISSUE THREAD

**Issue by mshoho** [rpetrich/babel-plugin-transform-async-to-promises#62]
Hey,
`const` keyword is used in helpers.js.
When I build a module with tsdx (which uses babel-plugin-transform-async-to-promises) targeting es5, I get invalid result because of this `const`.

**Comment by pubkey** [comment]
Same problem here. Also using `export` makes a problem.
@rpetrich  can I make a PR that transpiles the helpers so that they work with es5?

**Comment by rpetrich** [comment]
In d795742cec84233000e32eeb264cd562b9a2fab5 helpers.js is now an ES5-compatible CommonJS module that legacy bundlers can require. Bundlers that support ES modules should instead use helpers.mjs. @pubkey, I tried this out on rxdb and your browserify build step now works.

**Comment by pubkey** [comment]
@rpetrich this is so awesome. Thank you very much

**Comment by rpetrich** [comment]
I'll mark this issue as closed.
