### ISSUE TITLE
Incorrect code for transformed class + conditional

### ISSUE THREAD

**Issue by joshkel** [rpetrich/babel-plugin-transform-async-to-promises#71]
A class method that only sometimes awaits is compiled incorrectly.

For example:

```js
class TestClass {
  async testMe(enabled) {
    if (!enabled) {
      return;
    }
    await doIt();
  }
}
```

is compiled to

```js
    function testMe(enabled) {
      try {
        if (!enabled) {
          return;
        }
        return _awaitIgnored(Promise.resolve());
      } catch (e) {
        return Promise.reject(e);
      }
    }
```

A function that calls this, expecting it to return a promise like an async function should, will fail.

The bug only manifests if @babel/plugin-transform-classes. A workaround is to add a spurious await (e.g., `await true;`) to the conditional block.

For a complete test case, see https://github.com/joshkel/async-bug.

**Comment by rpetrich** [comment]
Thanks for reporting. I traced this down to a bug with how return statements are rewritten inside named function expressions. There aren't any named function expressions in your source, but babel's transform-classes plugin converts methods to named function expressions before async-to-promises runs.

**Comment by joshkel** [comment]
Thanks!
