### ISSUE TITLE
Update to babel 7-beta?

### ISSUE THREAD

**Issue by ugin** [rpetrich/babel-plugin-transform-async-to-promises#9]
Could we update the plugin to use `"@babel/core": "7.0.0-beta.46"` and list `@babel/core` and `babylon` as dependencies? 

As peedDependencies it requires `babel-core` and doesn't work with v7.0.0-beta.

I would do a PR if agreed.

**Comment by ugin** [comment]
Removing `peerDependencies` and using `transformFromAst` from the babel instance did the trick. I've created a PR, let me know if something needs to change.

**Comment by rpetrich** [comment]
Fantastic. I've cherry-picked your commit. I'm going to work on integrating both babel versions into the tests before I ship to npm (and am leaving this issue open temporarily as a reminder)

**Comment by ugin** [comment]
I've tried to integrate v7 into the tests, but the hoisting functionality throws errors. Couldn't figure out if it's babel related or some logic needs to be updated.

This gist contains a the modified test file if you have time for a quick test: https://gist.github.com/ugin/d1b8974f48057c0adab65887a5a15ddc

A few things that changed:
- `babel.transformFromAst` -> `babel.transformFromAstSync`
- `babel.transformFromAstSync` needs option `{ ast: true }` to return the ast
- `types.cloneDeep(ast)` -> `types.cloneNode(ast, true)`

Tested against:

```
    "@babel/core": "^7.0.0-beta.46",
    "babylon": "^7.0.0-beta.46",
```

**Comment by rpetrich** [comment]
Babel 7 has trouble with tracking scope across some of the transformations async-to-promises performs. The `babel7` branch has a number of adjustments to resync the scope state in many cases. Function hoisting is still broken, but it's a start.

**Comment by kentcdodds** [comment]
Now that babel 7 is officially released maybe it's an ok time to upgrade to babel 7 completely?

**Comment by rpetrich** [comment]
With the exception of the `hoist` option being incompatible, babel 7 is fully supported now.

**Comment by BernsteinA** [comment]
not working with babel 7 and webpack, because you have `require("babylon")` without babylon in the dependencies

**Comment by rpetrich** [comment]
@BernsteinA good catch. I wasn't aware babylon was replaced with @babel/core in babel 7.
